# Generated by Django 4.1.7 on 2023-03-31 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[(0, 'Draft'), (1, 'Waiting approval'), (2, 'Active')], default=2, max_length=50),
        ),
    ]
