# Generated by Django 4.1.7 on 2023-03-31 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_deleted_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Draft'), (1, 'Waiting approval'), (2, 'Active')], default=2, max_length=50),
        ),
    ]
