# Generated by Django 4.1.7 on 2023-04-30 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='shop_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
