# Generated by Django 4.1.7 on 2023-05-09 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_breadcrumb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Breadcrumb',
        ),
    ]
