# Generated by Django 4.2.1 on 2023-05-15 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='thumbnail',
        ),
    ]
