# Generated by Django 4.2.1 on 2023-05-17 20:38

from django.db import migrations, models
import store.validators


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_remove_product_image_remove_product_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='default',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/product_images/', validators=[store.validators.validate_file_size]),
        ),
    ]
